import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
export const metadata: Metadata = {
  title: "Arpan Bhandari",
  description: "Generated by create next app",
};
const font = Roboto({
  weight: ["400", "500", "700", "900"],
  preload: true,
  style: ["italic", "normal"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"bg-[#002347] " + font.className}>{children}</body>
    </html>
  );
}
